### ISSUE TITLE
Equal sign ligature issue

### ISSUE THREAD

**Issue by donshius** [Silverwolf90/inconsolata-js-ligatures#1]
The ligature that should show for double equals signs show when there are 3 and nothing when there are 2.

**Comment by Silverwolf90** [comment]
Hi @donshius, this is by design -- please see the readme:

> This is a bit opinionated, as I never use == and != so I have the strict versions only take up 2 characters instead of 3.

I actually don't use this font anymore anyway. I switched to [Fira Code](https://github.com/tonsky/FiraCode).
